import { StyleSheet } from 'react-native';
const Styles = StyleSheet.create({
  dashboardMainContainer: {
    width: '100%',
    height: '100%',
    backgroundColor: '#fff',
    fontFamily: 'Poppins',
  },
  headerView: {
    marginTop: 5,
    width: '100%',
    height: 60,
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  avoidingKeyBoard: {
    // borderWidth: 1,
    // height:'100%',
    padding: 10,
    marginTop: 5,
    marginRight: 4,
    marginLeft: 4,
    marginBottom: 10,
    // borderColor: '#dededeff',
    // borderRadius:4,
    minHeight: 400,
    // elevation:1,
  },
  titleInput: {
    borderBottomWidth: 1,
    height: 40,
    fontSize: 18,
    borderBottomColor: '#dedede',
    fontWeight: 'bold',
    paddingLeft: 6,
    marginBottom: 6,
  },
  noteInfo: {
    paddingVertical: 6,
    paddingHorizontal: 10,
    // paddingTop: 4,
    // paddingLeft: 6,
    // paddingBottom: 10,
    // paddingRight: 6,
    fontFamily: 'Poppins',
    fontSize: 15,
    // minHeight:300,
    // borderWidth:1,
    // letterSpacing:2,
    // overflow: 'scroll',
    // textAlign: 'justify',
  },
});
export default Styles;
