import { StyleSheet } from 'react-native';
const Styles = StyleSheet.create({
  dashboardMainContainer: {
    width: '100%',
    height: '100%',
    backgroundColor: '#fff',
    fontFamily: 'Poppins',
  },
  headerView: {
    marginTop: 5,
    width: '100%',
    height: 60,
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  safeAreaViewStyles: {
    width: '100%',
    height: '90%',
    // borderWidth:2,
    // borderColor:'red',
    padding: 6,
    paddingLeft: 10,
    paddingRight: 10,
  },
  securityContainer: {
    width: '100%',
    height: 150,
    // borderWidth:2,
    // borderColor:'red',
    padding: 6,
    fontSize: 15,
    // backgroundColor:'#c1bebe22',
    fontFamily: 'Poppins',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 6,
    // elevation:1,
    // overflow:'hidden',
  },
  iconContainer: {
    width: 100,
    height: 100,
    // borderWidth:1,
    borderRadius: 200,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#dedede',
  },
  infoViewContainer: {
    width: '100%',
    height: 40,
    // borderWidth:2,
    // borderColor:'red',
    padding: 6,
    fontSize: 15,
    // backgroundColor:'#c1bebe22',
    fontFamily: 'Poppins',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 6,
    // elevation:1,
    // overflow:'hidden',
  },
  profileText: {
    fontSize: 20,
    fontWeight: 'bold',
  },
  profileMailText: {
    fontSize: 12,
    color: '#dedede',
  },
  counterContainer: {
    width: '100%',
    // borderWidth:2,
    // borderColor:'red',
    padding: 6,
    fontSize: 15,
    // backgroundColor:'#c1bebe22',
    fontFamily: 'Poppins',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexDirection: 'row',
    borderRadius: 6,
    // elevation:1,
    // overflow:'hidden',
  },
  allConutContainer: {
    width: 100,
    height: 60,
    // backgroundColor:'#dedede',
    margin: 4,
    justifyContent: 'center',
    alignItems: 'center',
  },
  middleCounterContainer: {
    borderLeftWidth: 2,
    borderRightWidth: 2,
    borderColor: '#dedede',
  },
  allConut: {
    fontSize: 18,
    fontWeight: 'bold',
  },
  countLabelText: {
    fontSize: 14,
    color: '#dedede',
  },
  labelHeadingText: {
    marginLeft: 10,
    marginTop: 10,
    fontWeight: 'bold',
    fontSize: 15,
    // backgroundColor:'#c1bebe66',
    // color:'#bbbbbb',
    fontFamily: 'Poppins',
    textAlign: 'left',
  },
  actionsSafeAreaViewContainer: {
    paddingTop: 10,
    paddingBottom: 20,
    // borderBottomWidth:1,
    borderColor: '#c2c2c2',
  },
  listItemContainer: {
    marginTop: 6,
    marginBottom: 6,
    width: '100%',
    height: 70,
    borderWidth: 1,
    borderColor: '#f1f1f1',
    borderRadius: 6,
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 10,
  },
  listItemContentContainer: {
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'row',
    marginLeft: 10,
    marginRight: 20,
  },
  labelTextContainer: {
    marginLeft: 20,
  },
  leftLabelText: {
    fontSize: 10,
    fontFamily: 'Poppins',
    marginLeft: 10,
    fontWeight: 'bold',
  },
  rightLabelText: {
    fontSize: 16,
    fontFamily: 'Poppins',
    marginLeft: 10,
    fontWeight: 'bold',
  },
});
export default Styles;
