import { StyleSheet } from 'react-native';
const Styles = StyleSheet.create({
  dashboardMainContainer: {
    width: '100%',
    height: '100%',
    backgroundColor: '#fff',
    fontFamily: 'Poppins',
  },
  headerView: {
    marginTop: 5,
    width: '100%',
    height: 60,
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  safeAreaViewContainer: {
    width: '100%',
    height: '90%',
    // borderWidth:2,
    // borderColor:'red',
    padding: 6,
    paddingLeft: 10,
    paddingRight: 10,
  },
  securityCheckUpMainContainer: {
    width: '100%',
    height: 150,
    // borderWidth:2,
    // borderColor:'red',
    padding: 6,
    fontSize: 15,
    backgroundColor: '#c1bebe22',
    fontFamily: 'Poppins',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 6,
    // elevation:1,
    // overflow:'hidden',
  },
  securityIconContainer: {
    width: 50,
    height: 50,
    // borderWidth:1,
    borderRadius: 100,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#78fg54ff',
  },
  securityCheckUpText: {
    fontSize: 15,
    // backgroundColor:'#c1bebe66',
    fontFamily: 'Poppins',
    textAlign: 'center',
  },
  verifiedText: {
    fontSize: 15,
    // backgroundColor:'#c1bebe66',
    fontFamily: 'Poppins',
    textAlign: 'center',
    color: 'green',
  },
  settingLabelText: {
    marginTop: 10,
    fontWeight: 'bold',
    fontSize: 15,
    // backgroundColor:'#c1bebe66',
    color: '#bbbbbb',
    fontFamily: 'Poppins',
    textAlign: 'left',
  },
  optionItemSafeAreaView: {
    paddingTop: 10,
    paddingBottom: 20,
    borderBottomWidth: 1,
    borderColor: '#c2c2c2',
  },
  menuItemsMainContainer: {
    width: '100%',
    height: 50,
    // borderWidth:2,
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  manuItemsContentContainer: {
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'row',
  },
  menuItemLabelText: {
    fontSize: 16,
    fontFamily: 'Poppins',
    marginLeft: 10,
    fontWeight: 'bold',
  },
  menuItemAction: {
    borderWidth: 1,
    padding: 4,
    paddingLeft: 15,
    paddingRight: 15,
    borderRadius: 5,
    borderColor: '#2560ff',
  },
  sideDrawerOptionalMenuItemContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    margin: 2,
    paddingVertical: 10,
  },
  sideDrawerDeleteAccountText: {
    fontWeight: 'bold',
    color: '#fff',
    fontSize: 16,
    marginHorizontal: 4,
  },
});
export default Styles;
